### PR TITLE
Added hardware breakpoints

### PR DESCRIPTION
**Pull request by kaolpr**
Added hardware breakpoints that got lost since https://github.com/litex-hub/pythondata-cpu-vexriscv/pull/5 was merged.

### CODE REVIEW

**Comment by kaolpr** [comment]
I'd opt for adding more variants. Hardware breakpoints happens to be useful from time to time. Alternatively, we could add additional variants only for Min and Lite, and keep hw breakpoints in other debug variants.

**Comment by Dolu1990** [comment]
Seems good to me (Alternatively, we could add additional variants only for Min and Lite, and keep hw breakpoints in other debug variants.)

**Comment by kaolpr** [comment]
OK, than I propose the following:

- add `LiteDebugHWBP` and `MiniDebugHWBP` variants,
- keep 2 hardware breakpoints in remaining debug variants.

If that is OK for you, I'll update PR.

**Comment by kaolpr** [comment]
Maybe, for Lite and Mini a single hw breakpoint would be enough?

**Comment by Dolu1990** [comment]
hmm, single hardware breakpoint is kind of tricky as for instance, some debuggers will by default use one at the start of the main function. So i would say 2 as a minimum

**Comment by tcal-x** [comment]
> hmm, single hardware breakpoint is kind of tricky as for instance, some debuggers will by default use one at the start of the main function. So i would say 2 as a minimum

Yes that is correct; it is a  software issue.   https://github.com/litex-hub/wishbone-utils/issues/30

**Comment by kaolpr** [comment]
I've added 2 new variants for Lite and Min with `HwBP` suffix. Other debug variants gets 2 breakpoints by default. If this PR is merged, I'll make PR for Litex to include support for those variants.

**Comment by Dolu1990** [comment]
Seems good to me, let's merge ?

**Comment by enjoy-digital** [comment]
Thanks @kaolpr, @Dolu1990, this is merged. (@Dolu1990 feel free to merge things here in the future when it seems good to you).

**Pull request merged**
